name: bg_remover_app
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.3

flutter:
  uses-material-design: true
  
