name: Jeeta_sms_app
description: Ranjit style secure SMS app with OTP login, profile, and dual SIM.
publish_to: 'none'

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
  
