name: bg_remover_app
description: A professional background remover app.
publish_to: 'none'

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image: ^4.1.3
  path_provider: ^2.1.2
  gal: ^2.2.0

flutter:
  uses-material-design: true
  
