name: Build Flutter APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Backup Custom Files & Generate Android
        run: |
          mkdir -p backup
          cp lib/main.dart backup/main.dart
          cp pubspec.yaml backup/pubspec.yaml
          flutter create . --platforms=android --project-name telegram_sms_app
          cp backup/main.dart lib/main.dart
          cp backup/pubspec.yaml pubspec.yaml
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Clean and Build APK
        run: |
          flutter clean
          flutter build apk --release
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
